(function(){
'use strict';
var KEY='writingvault_data_v1',LK='novalab_language_v1',timer=null,current=null,dirty=false,initial={};
var fields=['e-title','e-task','e-topic','e-topic-new','e-status','e-target','e-band','e-prompt','e-text','e-improved','e-notes'];
var T={vi:{saving:'Đang lưu...',saved:'Đã lưu bản nháp',failed:'Không thể lưu bản nháp.',found:'Bản nháp',resume:'Tiếp tục bản nháp',remove:'Xóa bản nháp',confirm:'Xóa bản nháp này?',blocked:'Biểu mẫu đang có nội dung. Hãy lưu hoặc mở Bài mới trước khi tiếp tục.',bad:'Một bản nháp hỏng đã được bỏ qua an toàn.'},en:{saving:'Saving...',saved:'Draft saved',failed:'The draft could not be saved.',found:'Drafts',resume:'Continue draft',remove:'Delete draft',confirm:'Delete this draft?',blocked:'The form contains content. Save it or open New essay before continuing.',bad:'A damaged draft was safely ignored.'}};
function tr(k){var l;try{l=localStorage.getItem(LK)==='en'?'en':'vi'}catch(e){l='vi'}return T[l][k]}function el(id){return document.getElementById(id)}function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)}
function read(){var raw=localStorage.getItem(KEY),d=raw?JSON.parse(raw):{};if(!d||typeof d!=='object'||Array.isArray(d))throw Error('bad-state');if(!Array.isArray(d.drafts))d.drafts=[];return d}function write(d){localStorage.setItem(KEY,JSON.stringify(d));if(window.S)S.drafts=d.drafts;if(window.SN&&SN.markModified)SN.markModified()}
function meaningful(){return['e-title','e-topic-new','e-prompt','e-text','e-improved','e-notes'].some(function(id){return String((el(id)||{}).value||'').trim()})||['e-target','e-band'].some(function(id){return el(id)&&el(id).value!==initial[id]})}
function value(){var old=read().drafts.find(function(x){return x&&x.draftId===current}),now=new Date().toISOString(),d={schemaVersion:1,draftId:current||uid(),essayId:(el('essay-id')||{}).value||'',createdAt:old&&old.createdAt||now,updatedAt:now};var names={title:'e-title',task:'e-task',topic:'e-topic',topicNew:'e-topic-new',status:'e-status',targetBand:'e-target',band:'e-band',prompt:'e-prompt',essayText:'e-text',improvedVersion:'e-improved',notes:'e-notes'};Object.keys(names).forEach(function(k){d[k]=(el(names[k])||{}).value||''});return d}
function status(s,bad){var n=el('wv-draft-status');if(n){n.textContent=s;n.style.color=bad?'#fb7185':'var(--t3)'}}
function saveNow(show){clearTimeout(timer);if(!dirty&&!show)return true;if(!meaningful())return true;try{status(tr('saving'));var d=read(),v=value();current=v.draftId;var i=d.drafts.findIndex(function(x){return x&&x.draftId===current});if(i<0)d.drafts.unshift(v);else d.drafts[i]=v;write(d);dirty=false;status(tr('saved')+' · '+new Date(v.updatedAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}));render();return true}catch(e){console.error('Draft save failed',e);status(tr('failed'),true);if(show)alert(tr('failed'));return false}}
function schedule(){dirty=true;status(tr('saving'));clearTimeout(timer);timer=setTimeout(saveNow,1000)}function clearInitial(){['e-target','e-band'].forEach(function(id){initial[id]=(el(id)||{}).value||''})}
function restore(id){try{var d=read().drafts.find(function(x){return x&&x.draftId===id&&x.schemaVersion===1});if(!d)throw Error('bad-draft');if(meaningful()&&current!==id)return alert(tr('blocked'));current=id;if(el('essay-id'))el('essay-id').value=d.essayId||'';var names={title:'e-title',task:'e-task',topic:'e-topic',topicNew:'e-topic-new',status:'e-status',targetBand:'e-target',band:'e-band',prompt:'e-prompt',essayText:'e-text',improvedVersion:'e-improved',notes:'e-notes'};Object.keys(names).forEach(function(k){if(el(names[k]))el(names[k]).value=d[k]||''});if(typeof syncTopicSelects==='function')syncTopicSelects();if(typeof liveStats==='function')liveStats();dirty=false;clearInitial();status(tr('saved'));render()}catch(e){console.error(e);alert(tr('bad'))}}
function remove(id){if(!confirm(tr('confirm')))return;try{var d=read();d.drafts=d.drafts.filter(function(x){return x&&x.draftId!==id});write(d);if(current===id)current=null;render()}catch(e){console.error(e);alert(tr('failed'))}}
function button(label,fn){var b=document.createElement('button');b.type='button';b.className='btn btn-sm';b.textContent=label;b.setAttribute('aria-label',label);b.addEventListener('click',fn);return b}
function render(){var box=el('wv-draft-list');if(!box)return;box.replaceChildren();try{var drafts=read().drafts.filter(function(d){return d&&d.schemaVersion===1&&typeof d.draftId==='string'});if(!drafts.length)return;var title=document.createElement('b');title.textContent=tr('found');box.appendChild(title);drafts.forEach(function(d){var row=document.createElement('div');row.style.cssText='display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-top:7px';var text=document.createElement('span');text.style.flex='1';text.textContent=(d.title||d.task||'—')+' · '+(d.topicNew||d.topic||'—')+' · '+new Date(d.updatedAt).toLocaleString();row.append(text,button(tr('resume'),function(){restore(d.draftId)}),button(tr('remove'),function(){remove(d.draftId)}));box.appendChild(row)})}catch(e){console.error('Draft list failed',e);box.textContent=tr('bad')}}
function init(){var msg=el('write-msg');if(!msg)return;var st=document.createElement('div');st.id='wv-draft-status';st.className='mini';st.setAttribute('role','status');st.setAttribute('aria-live','polite');var list=document.createElement('div');list.id='wv-draft-list';list.className='info-box';msg.before(st,list);clearInitial();fields.forEach(function(id){var n=el(id);if(n){n.addEventListener('input',schedule);n.addEventListener('change',schedule)}});var n=window.newEssay,l=window.loadEssay,s=window.saveEssay;window.newEssay=function(){if(dirty&&!saveNow(true))return false;var r=n.apply(this,arguments);current=uid();dirty=false;clearInitial();return r};window.loadEssay=function(){if(dirty&&!saveNow(true))return false;var r=l.apply(this,arguments);current=uid();dirty=false;clearInitial();return r};window.saveEssay=function(){if(dirty&&!saveNow(true))return false;var r=s.apply(this,arguments);var essayId=(el('essay-id')||{}).value;if(r===true&&essayId&&typeof getEssay==='function'&&getEssay(essayId)){try{var d=read();d.drafts=d.drafts.filter(function(x){return x&&x.draftId!==current});write(d);current=uid();dirty=false;render()}catch(e){console.error(e);return false}}return r};document.addEventListener('visibilitychange',function(){if(document.visibilityState==='hidden')saveNow()});window.addEventListener('pagehide',function(){saveNow()});window.addEventListener('studynova-language-change',render);window.addEventListener('storage',function(e){if(e.key===LK)render()});render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
