(function () {
  "use strict";
  var timer = null, currentDraftId = null, dirty = false, KEY = "writingvault_data_v1", LANG_KEY = "novalab_language_v1";
  var fields = ["e-title", "e-task", "e-topic", "e-topic-new", "e-status", "e-target", "e-band", "e-prompt", "e-text", "e-improved", "e-notes"];
  var tx = { vi: { saving:"Đang lưu...", saved:"Đã lưu bản nháp", at:"Đã lưu lúc ", failed:"Lưu bản nháp thất bại", found:"Có bản nháp chưa hoàn thành", resume:"Tiếp tục bản nháp", remove:"Xóa bản nháp", ignore:"Bỏ qua", bad:"Bản nháp bị lỗi và đã được bỏ qua an toàn.", confirm:"Xóa bản nháp này?", blocked:"Không thể lưu bản nháp. Nội dung hiện tại được giữ nguyên." }, en: { saving:"Saving...", saved:"Draft saved", at:"Saved at ", failed:"Failed to save draft", found:"An unfinished draft was found", resume:"Continue draft", remove:"Delete draft", ignore:"Ignore", bad:"A damaged draft was safely ignored.", confirm:"Delete this draft?", blocked:"The draft could not be saved. Current content was left unchanged." } };
  function tr(k) { return tx[localStorage.getItem(LANG_KEY) === "en" ? "en" : "vi"][k]; }
  function el(id) { return document.getElementById(id); }
  function id() { return crypto.randomUUID ? crypto.randomUUID() : Date.now().toString(36) + Math.random().toString(36).slice(2); }
  function state() { var raw = localStorage.getItem(KEY), value = raw ? JSON.parse(raw) : {}; if (!value || typeof value !== "object") value = {}; if (!Array.isArray(value.drafts)) value.drafts = []; return value; }
  function formEmpty() { return !fields.some(function (name) { var node = el(name); return node && String(node.value || "").trim(); }); }
  function draft() { var old = state().drafts.find(function (x) { return x.draftId === currentDraftId; }); var out = { schemaVersion:1, draftId:currentDraftId || id(), essayId:(el("essay-id") || {}).value || "", createdAt:old && old.createdAt || new Date().toISOString(), updatedAt:new Date().toISOString() }; fields.forEach(function (name) { out[name.replace(/^e-/, "")] = (el(name) || {}).value || ""; }); return out; }
  function status(text, bad) { var node = el("wv-draft-status"); if (node) { node.textContent = text; node.style.color = bad ? "#fb7185" : "var(--t3)"; } }
  function saveNow(show) { clearTimeout(timer); if (!dirty && !show) return true; try { if (formEmpty()) return true; status(tr("saving")); var data = state(), value = draft(); currentDraftId = value.draftId; var pos = data.drafts.findIndex(function (x) { return x.draftId === currentDraftId; }); if (pos < 0) data.drafts.unshift(value); else data.drafts[pos] = value; localStorage.setItem(KEY, JSON.stringify(data)); if (typeof S !== "undefined") S.drafts = data.drafts; dirty = false; status(tr("at") + new Date(value.updatedAt).toLocaleTimeString([], { hour:"2-digit", minute:"2-digit" })); render(); return true; } catch (e) { console.error("Writing draft save failed", e); status(tr("failed"), true); if (show) alert(tr("blocked")); return false; } }
  function schedule() { dirty = true; status(tr("saving")); clearTimeout(timer); timer = setTimeout(saveNow, 1000); }
  function restore(draftId) { try { var value = state().drafts.find(function (x) { return x.draftId === draftId; }); if (!value || (!formEmpty() && currentDraftId !== draftId)) return; currentDraftId = value.draftId; if (el("essay-id")) el("essay-id").value = value.essayId || ""; fields.forEach(function (name) { if (el(name)) el(name).value = value[name.replace(/^e-/, "")] || ""; }); if (typeof syncTopicSelects === "function") syncTopicSelects(); if (typeof liveStats === "function") liveStats(); status(tr("saved")); dirty = false; render(); } catch (e) { console.error("Writing draft restore failed", e); alert(tr("bad")); } }
  function remove(draftId) { if (!confirm(tr("confirm"))) return; try { var data = state(); data.drafts = data.drafts.filter(function (x) { return x.draftId !== draftId; }); localStorage.setItem(KEY, JSON.stringify(data)); if (typeof S !== "undefined") S.drafts = data.drafts; if (currentDraftId === draftId) currentDraftId = null; render(); } catch (e) { console.error("Writing draft delete failed", e); alert(tr("failed")); } }
  function render() { var box = el("wv-draft-list"); if (!box) return; try { var drafts = state().drafts; box.innerHTML = drafts.length ? "<b>" + tr("found") + "</b>" + drafts.map(function (d) { return '<div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-top:7px"><span style="flex:1">' + (d.title || (d.task === "task1" ? "Task 1" : "Task 2")) + " · " + (d.topic || "—") + " · " + new Date(d.updatedAt).toLocaleString() + '</span><button class="btn btn-blue btn-sm" data-draft-restore="' + d.draftId + '">' + tr("resume") + '</button><button class="btn btn-red btn-sm" data-draft-delete="' + d.draftId + '">' + tr("remove") + "</button></div>"; }).join("") : ""; box.querySelectorAll("[data-draft-restore]").forEach(function (b) { b.onclick = function () { restore(b.dataset.draftRestore); }; }); box.querySelectorAll("[data-draft-delete]").forEach(function (b) { b.onclick = function () { remove(b.dataset.draftDelete); }; }); } catch (e) { console.error("Writing draft list failed", e); box.textContent = tr("bad"); } }
  function init() { var writeMsg = el("write-msg"); if (!writeMsg) return; writeMsg.insertAdjacentHTML("beforebegin", '<div id="wv-draft-status" class="mini" role="status" aria-live="polite" style="margin:8px 0"></div><div id="wv-draft-list" class="info-box" style="margin:8px 0"></div>'); fields.forEach(function (name) { var node = el(name); if (node) { node.addEventListener("input", schedule); node.addEventListener("change", schedule); } });
    var originalNew = window.newEssay, originalLoad = window.loadEssay, originalSave = window.saveEssay;
    window.newEssay = function () { if (dirty && !saveNow(true)) return; currentDraftId = id(); dirty = false; return originalNew.apply(this, arguments); };
    window.loadEssay = function () { if (dirty && !saveNow(true)) return; var result = originalLoad.apply(this, arguments); currentDraftId = id(); dirty = false; return result; };
    window.saveEssay = function () { var before = (el("essay-id") || {}).value, result; try { result = originalSave.apply(this, arguments); var essayId = (el("essay-id") || {}).value; if (essayId && (essayId !== before || typeof getEssay !== "function" || getEssay(essayId))) { var data = state(); data.drafts = data.drafts.filter(function (x) { return x.draftId !== currentDraftId; }); localStorage.setItem(KEY, JSON.stringify(data)); if (typeof S !== "undefined") S.drafts = data.drafts; currentDraftId = id(); dirty = false; render(); } return result; } catch (e) { schedule(); throw e; } };
    document.addEventListener("visibilitychange", function () { if (document.visibilityState === "hidden") saveNow(); }); window.addEventListener("pagehide", function () { saveNow(); }); window.addEventListener("storage", function (e) { if (e.key === LANG_KEY) render(); }); render();
  }
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", init); else init();
})();
